"""fix doctor schedule table 

Revision ID: 0f2a7b899f36
Revises: a16f35612205
Create Date: 2025-12-13 23:21:29.123801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f2a7b899f36'
down_revision: Union[str, Sequence[str], None] = 'a16f35612205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_schedule', sa.Column('days', sa.String(length=255), nullable=False))
    op.add_column('doctor_schedule', sa.Column('hours', sa.String(length=255), nullable=False))
    op.alter_column('doctor_schedule', 'doctor_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('doctor_schedule', 'end_time')
    op.drop_column('doctor_schedule', 'day_of_week')
    op.drop_column('doctor_schedule', 'start_time')
    op.add_column('doctor_schedule_registration', sa.Column('days', sa.String(length=255), nullable=False))
    op.add_column('doctor_schedule_registration', sa.Column('hours', sa.String(length=255), nullable=False))
    op.alter_column('doctor_schedule_registration', 'registration_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('doctor_schedule_registration', 'end_time')
    op.drop_column('doctor_schedule_registration', 'day_of_week')
    op.drop_column('doctor_schedule_registration', 'start_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_schedule_registration', sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('doctor_schedule_registration', sa.Column('day_of_week', sa.VARCHAR(length=3), autoincrement=False, nullable=False))
    op.add_column('doctor_schedule_registration', sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.alter_column('doctor_schedule_registration', 'registration_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('doctor_schedule_registration', 'hours')
    op.drop_column('doctor_schedule_registration', 'days')
    op.add_column('doctor_schedule', sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('doctor_schedule', sa.Column('day_of_week', sa.VARCHAR(length=3), autoincrement=False, nullable=False))
    op.add_column('doctor_schedule', sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.alter_column('doctor_schedule', 'doctor_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('doctor_schedule', 'hours')
    op.drop_column('doctor_schedule', 'days')
    # ### end Alembic commands ###
