"""fix doctor table

Revision ID: 1e54b702af0b
Revises: fa70b0be8ab9
Create Date: 2025-12-13 22:39:34.415900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e54b702af0b'
down_revision: Union[str, Sequence[str], None] = 'fa70b0be8ab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_registration', sa.Column('doctor_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'doctor_registration', 'doctor', ['doctor_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'doctor_registration', type_='foreignkey')
    op.drop_column('doctor_registration', 'doctor_id')
    # ### end Alembic commands ###
