"""Add roles in tables

Revision ID: 70d3a6e71ee4
Revises: 7ae9783a9d58
Create Date: 2025-12-13 10:42:32.261700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '70d3a6e71ee4'
down_revision: Union[str, Sequence[str], None] = '7ae9783a9d58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

user_role_enum = postgresql.ENUM(
    "super_admin",
    "admin",
    name="user_role_enum"
)


def upgrade():
    user_role_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "user",
        sa.Column(
            "role",
            user_role_enum,
            nullable=False,
            server_default="admin"
        )
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
