"""add colleague table

Revision ID: 7ae9783a9d58
Revises: f8f3c1e48bcc
Create Date: 2025-12-08 09:03:33.748512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ae9783a9d58'
down_revision: Union[str, Sequence[str], None] = 'f8f3c1e48bcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colleague',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('national_number', sa.String(length=50), nullable=False),
    sa.Column('major', sa.String(length=255), nullable=True),
    sa.Column('experience_in_current', sa.Integer(), nullable=True),
    sa.Column('experience_in_major', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('current_work_address', sa.Text(), nullable=True),
    sa.Column('card_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='contentstatus'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('colleague_registration',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('national_number', sa.String(length=50), nullable=False),
    sa.Column('major', sa.String(length=255), nullable=True),
    sa.Column('experience_in_current', sa.Integer(), nullable=False),
    sa.Column('experience_in_major', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('current_work_address', sa.Text(), nullable=True),
    sa.Column('card_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='contentstatus'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('colleague_registration')
    op.drop_table('colleague')
    # ### end Alembic commands ###
