"""complete Doctor Registration tables

Revision ID: a16f35612205
Revises: 1e87af47d5d7
Create Date: 2025-12-13 22:51:14.688064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a16f35612205'
down_revision: Union[str, Sequence[str], None] = '1e87af47d5d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_field_registration',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('registration_id', sa.UUID(), nullable=True),
    sa.Column('field_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['registration_id'], ['doctor_registration.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctor_schedule_registration',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('registration_id', sa.UUID(), nullable=True),
    sa.Column('day_of_week', sa.String(length=3), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['registration_id'], ['doctor_registration.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('doctor_registration_doctor_id_fkey'), 'doctor_registration', type_='foreignkey')
    op.drop_column('doctor_registration', 'doctor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_registration', sa.Column('doctor_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('doctor_registration_doctor_id_fkey'), 'doctor_registration', 'doctor', ['doctor_id'], ['id'], ondelete='SET NULL')
    op.drop_table('doctor_schedule_registration')
    op.drop_table('doctor_field_registration')
    # ### end Alembic commands ###
