"""fix doctor and colleague tables

Revision ID: a671088b9053
Revises: f26e5361ef7a
Create Date: 2025-12-06 11:32:11.961985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a671088b9053'
down_revision: Union[str, Sequence[str], None] = 'f26e5361ef7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doctor_field', 'doctor_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('doctor_registration', sa.Column('doctor_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'doctor_registration', ['doctor_id'])
    op.create_foreign_key(None, 'doctor_registration', 'doctor', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.drop_column('doctor_registration', 'experience_in_current')
    op.drop_column('doctor_registration', 'current_work_address')
    op.drop_column('doctor_registration', 'city')
    op.drop_column('doctor_registration', 'national_number')
    op.drop_column('doctor_registration', 'full_name')
    op.drop_column('doctor_registration', 'phone_number')
    op.drop_column('doctor_registration', 'card_url')
    op.drop_column('doctor_registration', 'major')
    op.drop_column('doctor_registration', 'state')
    op.drop_column('doctor_registration', 'experience_in_major')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_registration', sa.Column('experience_in_major', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('doctor_registration', sa.Column('state', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('doctor_registration', sa.Column('major', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('doctor_registration', sa.Column('card_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('doctor_registration', sa.Column('phone_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('doctor_registration', sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('doctor_registration', sa.Column('national_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('doctor_registration', sa.Column('city', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('doctor_registration', sa.Column('current_work_address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('doctor_registration', sa.Column('experience_in_current', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'doctor_registration', type_='foreignkey')
    op.drop_constraint(None, 'doctor_registration', type_='unique')
    op.drop_column('doctor_registration', 'doctor_id')
    op.alter_column('doctor_field', 'doctor_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
