"""fix some problems

Revision ID: f26e5361ef7a
Revises: 180dd5ff3e8c
Create Date: 2025-12-04 11:51:03.643167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f26e5361ef7a'
down_revision: Union[str, Sequence[str], None] = '180dd5ff3e8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('seo_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'article', 'seo_settings', ['seo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_column('article', 'seo_id')
    # ### end Alembic commands ###
