"""fix colleagu table

Revision ID: fa70b0be8ab9
Revises: 70d3a6e71ee4
Create Date: 2025-12-13 19:37:57.442598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa70b0be8ab9'
down_revision: Union[str, Sequence[str], None] = '70d3a6e71ee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'colleague', ['national_number'])
    op.add_column('colleague_registration', sa.Column('colleague_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'colleague_registration', ['national_number'])
    op.create_foreign_key(None, 'colleague_registration', 'colleague', ['colleague_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'colleague_registration', type_='foreignkey')
    op.drop_constraint(None, 'colleague_registration', type_='unique')
    op.drop_column('colleague_registration', 'colleague_id')
    op.drop_constraint(None, 'colleague', type_='unique')
    # ### end Alembic commands ###
