"""fix some issues

Revision ID: fff82d7d97c9
Revises: a1481fa86240
Create Date: 2025-12-06 14:13:07.283262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fff82d7d97c9'
down_revision: Union[str, Sequence[str], None] = 'a1481fa86240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_registration', sa.Column('full_name', sa.String(length=255), nullable=False))
    op.add_column('doctor_registration', sa.Column('position', sa.String(length=255), nullable=False))
    op.add_column('doctor_registration', sa.Column('major', sa.String(length=255), nullable=False))
    op.add_column('doctor_registration', sa.Column('university', sa.String(length=255), nullable=True))
    op.add_column('doctor_registration', sa.Column('experience_years', sa.Integer(), nullable=True))
    op.add_column('doctor_registration', sa.Column('picture_url', sa.Text(), nullable=True))
    op.add_column('doctor_registration', sa.Column('note', sa.Text(), nullable=True))
    op.drop_constraint(op.f('doctor_registration_doctor_id_key'), 'doctor_registration', type_='unique')
    op.drop_constraint(op.f('doctor_registration_doctor_id_fkey'), 'doctor_registration', type_='foreignkey')
    op.drop_column('doctor_registration', 'doctor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_registration', sa.Column('doctor_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('doctor_registration_doctor_id_fkey'), 'doctor_registration', 'doctor', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('doctor_registration_doctor_id_key'), 'doctor_registration', ['doctor_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('doctor_registration', 'note')
    op.drop_column('doctor_registration', 'picture_url')
    op.drop_column('doctor_registration', 'experience_years')
    op.drop_column('doctor_registration', 'university')
    op.drop_column('doctor_registration', 'major')
    op.drop_column('doctor_registration', 'position')
    op.drop_column('doctor_registration', 'full_name')
    # ### end Alembic commands ###
